### PR TITLE
Fix bug with uninitialized variable

### PR DESCRIPTION
**Pull request by oxayotl**
Sorry sorry sorry, yesterday when I simplified my code in a hurry I let a big with uninitialized variable slip. This should fix it. Sorry again!

### CODE REVIEW

**Comment by ai** [comment]
Don't worry, I will release it soon

**Comment by oxayotl** [comment]
Thanks!!

**Comment by ai** [comment]
Pushed to https://extensions.gnome.org/

**Comment by oxayotl** [comment]
Works like a charm, thanks a lot :+1:

**Pull request merged**
